name: Run Test

on:
  workflow_dispatch:

jobs:
  run-test:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: pip install parsl==2024.04.15

      - name: Run test
        run: python test.py